# Generated by Django 4.0 on 2021-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
