# Generated by Django 4.0 on 2021-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_bb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Контакт'),
        ),
    ]
