# Generated by Django 4.0 on 2021-12-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_bb_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='contact',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Контакт'),
        ),
    ]
